name: Trigger rebuild of parent repo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    container: alpine/httpie
    steps:
      - name: Notify parent repo
        run: http post Authorization:"token ${{ secrets.NOTIFY_TOKEN }} event_type=build https://api.github.com/repos/sesh/brntn.me/dispatches
