name: Trigger rebuild of parent repo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger build of parent repo
        run: |
          curl -H "Authorization: token ${{secrets.NOTIFY_TOKEN}}" \
            --request POST \
            --data '{"event_type": "build"}' \
            https://api.github.com/repos/sesh/brntn.me/dispatches
